/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as FinishRouteImport } from './routes/finish'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppSlugRouteImport } from './routes/app.$slug'
import { Route as ApiSubmitSessionRouteImport } from './routes/api/submit-session'
import { Route as ApiSaveRecordingRouteImport } from './routes/api/save-recording'
import { Route as AdminSignupRouteImport } from './routes/admin.signup'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEditorRouteImport } from './routes/admin.editor'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AppSlugIndexRouteImport } from './routes/app.$slug.index'
import { Route as ApiAdminSignupRouteImport } from './routes/api/admin.signup'

const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishRoute = FinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/app/$slug',
  path: '/app/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitSessionRoute = ApiSubmitSessionRouteImport.update({
  id: '/api/submit-session',
  path: '/api/submit-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveRecordingRoute = ApiSaveRecordingRouteImport.update({
  id: '/api/save-recording',
  path: '/api/save-recording',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/admin/editor',
  path: '/admin/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/admin/codes',
  path: '/admin/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugIndexRoute = AppSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugRoute,
} as any)
const ApiAdminSignupRoute = ApiAdminSignupRouteImport.update({
  id: '/api/admin/signup',
  path: '/api/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finish': typeof FinishRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/signup': typeof AdminSignupRoute
  '/api/save-recording': typeof ApiSaveRecordingRoute
  '/api/submit-session': typeof ApiSubmitSessionRoute
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/admin/signup': typeof ApiAdminSignupRoute
  '/app/$slug/': typeof AppSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finish': typeof FinishRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/signup': typeof AdminSignupRoute
  '/api/save-recording': typeof ApiSaveRecordingRoute
  '/api/submit-session': typeof ApiSubmitSessionRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/signup': typeof ApiAdminSignupRoute
  '/app/$slug': typeof AppSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finish': typeof FinishRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/signup': typeof AdminSignupRoute
  '/api/save-recording': typeof ApiSaveRecordingRoute
  '/api/submit-session': typeof ApiSubmitSessionRoute
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/admin/signup': typeof ApiAdminSignupRoute
  '/app/$slug/': typeof AppSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finish'
    | '/review'
    | '/screening'
    | '/admin/codes'
    | '/admin/editor'
    | '/admin/login'
    | '/admin/review'
    | '/admin/signup'
    | '/api/save-recording'
    | '/api/submit-session'
    | '/app/$slug'
    | '/admin/'
    | '/api/admin/signup'
    | '/app/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finish'
    | '/review'
    | '/screening'
    | '/admin/codes'
    | '/admin/editor'
    | '/admin/login'
    | '/admin/review'
    | '/admin/signup'
    | '/api/save-recording'
    | '/api/submit-session'
    | '/admin'
    | '/api/admin/signup'
    | '/app/$slug'
  id:
    | '__root__'
    | '/'
    | '/finish'
    | '/review'
    | '/screening'
    | '/admin/codes'
    | '/admin/editor'
    | '/admin/login'
    | '/admin/review'
    | '/admin/signup'
    | '/api/save-recording'
    | '/api/submit-session'
    | '/app/$slug'
    | '/admin/'
    | '/api/admin/signup'
    | '/app/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinishRoute: typeof FinishRoute
  ReviewRoute: typeof ReviewRoute
  ScreeningRoute: typeof ScreeningRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminEditorRoute: typeof AdminEditorRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminSignupRoute: typeof AdminSignupRoute
  ApiSaveRecordingRoute: typeof ApiSaveRecordingRoute
  ApiSubmitSessionRoute: typeof ApiSubmitSessionRoute
  AppSlugRoute: typeof AppSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminSignupRoute: typeof ApiAdminSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finish': {
      id: '/finish'
      path: '/finish'
      fullPath: '/finish'
      preLoaderRoute: typeof FinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/app/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-session': {
      id: '/api/submit-session'
      path: '/api/submit-session'
      fullPath: '/api/submit-session'
      preLoaderRoute: typeof ApiSubmitSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-recording': {
      id: '/api/save-recording'
      path: '/api/save-recording'
      fullPath: '/api/save-recording'
      preLoaderRoute: typeof ApiSaveRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/admin/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/admin/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug/': {
      id: '/app/$slug/'
      path: '/'
      fullPath: '/app/$slug/'
      preLoaderRoute: typeof AppSlugIndexRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/api/admin/signup': {
      id: '/api/admin/signup'
      path: '/api/admin/signup'
      fullPath: '/api/admin/signup'
      preLoaderRoute: typeof ApiAdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSlugRouteChildren {
  AppSlugIndexRoute: typeof AppSlugIndexRoute
}

const AppSlugRouteChildren: AppSlugRouteChildren = {
  AppSlugIndexRoute: AppSlugIndexRoute,
}

const AppSlugRouteWithChildren =
  AppSlugRoute._addFileChildren(AppSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinishRoute: FinishRoute,
  ReviewRoute: ReviewRoute,
  ScreeningRoute: ScreeningRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminEditorRoute: AdminEditorRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminSignupRoute: AdminSignupRoute,
  ApiSaveRecordingRoute: ApiSaveRecordingRoute,
  ApiSubmitSessionRoute: ApiSubmitSessionRoute,
  AppSlugRoute: AppSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminSignupRoute: ApiAdminSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
