/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as FinishRouteImport } from './routes/finish'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubmitSessionRouteImport } from './routes/api/submit-session'
import { Route as ApiSaveRecordingRouteImport } from './routes/api/save-recording'

const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishRoute = FinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitSessionRoute = ApiSubmitSessionRouteImport.update({
  id: '/api/submit-session',
  path: '/api/submit-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveRecordingRoute = ApiSaveRecordingRouteImport.update({
  id: '/api/save-recording',
  path: '/api/save-recording',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finish': typeof FinishRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/api/save-recording': typeof ApiSaveRecordingRoute
  '/api/submit-session': typeof ApiSubmitSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finish': typeof FinishRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/api/save-recording': typeof ApiSaveRecordingRoute
  '/api/submit-session': typeof ApiSubmitSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finish': typeof FinishRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/api/save-recording': typeof ApiSaveRecordingRoute
  '/api/submit-session': typeof ApiSubmitSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finish'
    | '/review'
    | '/screening'
    | '/api/save-recording'
    | '/api/submit-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finish'
    | '/review'
    | '/screening'
    | '/api/save-recording'
    | '/api/submit-session'
  id:
    | '__root__'
    | '/'
    | '/finish'
    | '/review'
    | '/screening'
    | '/api/save-recording'
    | '/api/submit-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinishRoute: typeof FinishRoute
  ReviewRoute: typeof ReviewRoute
  ScreeningRoute: typeof ScreeningRoute
  ApiSaveRecordingRoute: typeof ApiSaveRecordingRoute
  ApiSubmitSessionRoute: typeof ApiSubmitSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finish': {
      id: '/finish'
      path: '/finish'
      fullPath: '/finish'
      preLoaderRoute: typeof FinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-session': {
      id: '/api/submit-session'
      path: '/api/submit-session'
      fullPath: '/api/submit-session'
      preLoaderRoute: typeof ApiSubmitSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-recording': {
      id: '/api/save-recording'
      path: '/api/save-recording'
      fullPath: '/api/save-recording'
      preLoaderRoute: typeof ApiSaveRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinishRoute: FinishRoute,
  ReviewRoute: ReviewRoute,
  ScreeningRoute: ScreeningRoute,
  ApiSaveRecordingRoute: ApiSaveRecordingRoute,
  ApiSubmitSessionRoute: ApiSubmitSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
